<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>hmkd</string>
	</array>
	<key>name</key>
	<string>HatenaMarkdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>見出し1</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h1.hmkd</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>見出し2</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h2.hmkd</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>見出し3</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#\#\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h3.hmkd</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>見出し4</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#\#\#\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h4.hmkd</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>見出し5</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#\#\#\#\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h5.hmkd</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>見出し6</string>
			<key>match</key>
			<string>^(?&lt;!\\)\#\#\#\#\#\#(?!\#)(.*)$</string>
			<key>name</key>
			<string>variable.parameter.h6.hmkd</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?!\\)((\s)*\*)\s(\[(x){0,1}\])\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.bullet.begin</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.bullet.checkbox</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.bullet.checkbox.check</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>箇条書き チェックボックス</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>constant.character.bullet.begin</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(.)</string>
					<key>name</key>
					<string>string.other.bullet.contents</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?!\\)((\s)*\*)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.bullet.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>箇条書き</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>constant.character.bullet.begin</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(.)</string>
					<key>name</key>
					<string>string.other.bullet.contents</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.list.content</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>番号付きリスト</string>
			<key>match</key>
			<string>(?:[0-9]+)\.(?:\ ){1}(.*)</string>
			<key>name</key>
			<string>constant.character.list.begin</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>改行用の行末ダブルスペース</string>
			<key>match</key>
			<string>\ \ $</string>
			<key>name</key>
			<string>entity.name.function.newline</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>bold用 *hoge* &lt;em&gt;</string>
			<key>match</key>
			<string>(?&lt;!\\)\*(.)*(?=\*)(\*)</string>
			<key>name</key>
			<string>entity.name.function.bold</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>bold用 *hoge*</string>
			<key>match</key>
			<string>(?&lt;!\\)\*\*(.)*(?=\*)(\*\*)</string>
			<key>name</key>
			<string>entity.name.function.bold</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>続きを読む</string>
			<key>match</key>
			<string>\&lt;\!\-\-\ more\ \-\-\&gt;</string>
			<key>name</key>
			<string>entity.name.function.more</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>目次</string>
			<key>match</key>
			<string>\[\:contents\]</string>
			<key>name</key>
			<string>entity.name.function.contents</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\|</string>
			<key>comment</key>
			<string>表組み記法</string>
			<key>end</key>
			<string>\|$</string>
			<key>name</key>
			<string>entity.name.function.table.content</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>改行タグのみ</string>
			<key>match</key>
			<string>\&lt;(?:/*)br(?:/*)\&gt;</string>
			<key>name</key>
			<string>comment.line.break.normal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>改行タグ スタイル指定</string>
			<key>match</key>
			<string>\&lt;(?:/*)br(?:/*)\ (.+)\=(.+)\&gt;</string>
			<key>name</key>
			<string>comment.line.break.style</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;span\ style\=(\"(?:color|background)\:)\ (\#[a-fA-F0-9]{6})(\")\&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.token</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.style.color.colorcode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.token</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>文字色/背景色</string>
			<key>end</key>
			<string>\&lt;\/span\&gt;</string>
			<key>name</key>
			<string>entity.name.function.style.color</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(.*)</string>
					<key>name</key>
					<string>storage.type.style.color.destination</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;strike\&gt;</string>
			<key>comment</key>
			<string>打ち消し線(タグ)</string>
			<key>end</key>
			<string>\&lt;\/strike\&gt;</string>
			<key>name</key>
			<string>entity.name.function.strike</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(.)</string>
					<key>name</key>
					<string>keyword.control.strike.striked</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.blockquotes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.blockquotes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>引用</string>
			<key>match</key>
			<string>^(\&gt;+)(.*)$</string>
			<key>name</key>
			<string>constant.blockquotes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>水平線</string>
			<key>match</key>
			<string>^([\*\-\=](\s*)){3,}</string>
			<key>name</key>
			<string>entity.name.function.horizontalrule</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>打ち消し線</string>
			<key>match</key>
			<string>\~\~[^\n]*\~\~</string>
			<key>name</key>
			<string>constant.numeric.scratch</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>注釈</string>
			<key>match</key>
			<string>\(\(*.\)\)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\`\`\`)([a-zA-Z0-9]*)*((?=\:)\:.*)*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.code.highlight.start1</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.code.highlight.start2</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.highlight</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>コードハイライト</string>
			<key>end</key>
			<string>(^\`\`\`$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.code.highlight.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.other.code.highlight</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.code.highlight.codeblock</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(.)</string>
					<key>name</key>
					<string>storage.type.code.highligt.codeblock</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.code.oneliner.codeblock</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>一行コード</string>
			<key>match</key>
			<string>\`{1,2}([^\n]*?)(?&lt;!\\)\`{1,2}</string>
			<key>name</key>
			<string>constant.numeric.code.oneliner</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.embed.pict.title</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.pict.desc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>埋め込み画像</string>
			<key>match</key>
			<string>\!\[(.+)\]\(http(?:s*)\:\/\/.+?\ *((\"(.)*\"))*\)</string>
			<key>name</key>
			<string>entity.name.function.embed.pict</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.hatenaphoto.option</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>はてなフォト画像 ~~スニペット使うとバグりそうで怖い~~ 上手くいった</string>
			<key>match</key>
			<string>(?:\[f\:id\:hatenablog\:[0-9a-z]+\:image)+((\:w[0-9]+|\:left|\:right)*(?=\]))\]</string>
			<key>name</key>
			<string>entity.name.function.embed.hatenaphoto.frame</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.embed.textlink.</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.textlink.title</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>テキストリンク</string>
			<key>match</key>
			<string>\[([^\[\]]+)\]\(http(?:s{0,1})\:\/\/.+?\ *((\"(.)*\"))*\)</string>
			<key>name</key>
			<string>entity.name.function.embed.textlink</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.embedlink.option</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>埋め込みリンク</string>
			<key>match</key>
			<string>(?:^\[http(?:s??)\:\/\/.+?)((\:title|\:embed|\:cite)*(?=\]))\]</string>
			<key>name</key>
			<string>entity.name.function.embedlink.frame</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.taglink.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>タグリンク-タグパターン1</string>
			<key>match</key>
			<string>\[([^\[\]]*?)\]\[\]</string>
			<key>name</key>
			<string>entity.name.function.embed.taglink.frame</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.embed.taglink.desc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.taglink.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>タグリンク-タグパターン2</string>
			<key>match</key>
			<string>\[(.*?)\]\[(.*?)\]</string>
			<key>name</key>
			<string>entity.name.function.embed.taglink.frame</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.taglink.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>タグリンク-リンク</string>
			<key>match</key>
			<string>\[(.*)\]\:(?:http(?:s{0,1})\:\/\/|mailto\:)[^\s]*</string>
			<key>name</key>
			<string>entity.name.function.embed.taglink.link</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.embed.amazon.option</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>amazon商品リンク</string>
			<key>match</key>
			<string>\[asin\:[A-Z0-9]+(\:detail|\:image|\:large|\:title){1}\]</string>
			<key>name</key>
			<string>entity.name.function.embed.amazon.frame</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>htmlタグ コメント</string>
			<key>match</key>
			<string>\s*\&lt;\!\-\-\s*[^\-\&gt;]*\s*\-\-\&gt;</string>
			<key>name</key>
			<string>comment.line.double-slash.htmltag.comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.hmkd</string>
	<key>uuid</key>
	<string>e9f5d96b-6f81-40ac-a5d1-dc8ad40fe76e</string>
</dict>
</plist>
